### PR TITLE
fix: disallow collateralize and repay when eligible for liquidations

### LINKED ISSUE #135: Adding collateral should be disabled if the borrow is in liquidation [TD-5, TD-10, TD-11]
Avoids edge cases and race conditions during liquidation.

### PR DESCRIPTION
**Pull request by peer2f00l**

### CODE REVIEW

**Review by SmolinPavel — APPROVED** [review]

File: contract/market/src/impl_helper.rs [hunk 1]
```diff
@@ -315,13 +328,45 @@ impl Contract {
         }
     }
 
+    pub const GAS_FT_ON_TRANSFER_COLLATERALIZE_01_CONSUME_PRICE: Gas = Gas::from_tgas(5);
```
Comment (peer2f00l) [inline contract/market/src/impl_helper.rs:332]: These need to be measured
